### ISSUE TITLE
needs release on PyPI

### ISSUE THREAD

**Issue by michaelaye** [zonca/pytest-ipynb#16]
In order for my Travis tests to pass I need the latest fixes to appear on pip, could you push the fixes to Pypi please?

Thanks.

**Comment by zonca** [comment]
sure, I'd like to fix #15 later this week and make a release

**Comment by michaelaye** [comment]
Awesome. In the meantime I install it directly from github within Travis.

**Comment by zonca** [comment]
released 1.1.0, please test #17!
