### ISSUE TITLE
Is there a way to filter tests for Travis?

### ISSUE THREAD

**Issue by michaelaye** [zonca/pytest-ipynb#17]
If I would not want some tests to run with Travis, could I filter that somehow?

**Comment by zonca** [comment]
Not right now, what would be a good marker? Add "NOTRAVIS" in cell
description? Any better idea?

**Comment by michaelaye** [comment]
Not really. Anything is fine for me.

**Comment by zonca** [comment]
I'd like to check for the `CI` environmental variable and look for `SKIPCI` in test description

**Comment by michaelaye** [comment]
so funny, my brain wanted to read SKI-PCI all the time, and I wondered about this strange non-mnemonic acronym, until it make 'click' and I saw the SKIP-CI ;) Thanks for the implementation, will test it soon, but maybe upwards of 2 weeks, as i'm in proposal writing stress right now.
