### ISSUE TITLE
set working directory for notebook to its containing folder

### ISSUE THREAD

**Issue by machow** [zonca/pytest-ipynb#2]
When a notebook is loaded, (AFAIK) it's working directory is set to its containing folder. Is there any chance this could be implemented here? I'm interested in having examples in ipython notebooks, but being able to unit test them. I'm happy to look into implementing it if you have a sense for where the change would need to be made.

**Comment by zonca** [comment]
@machow can you provide a minimal example that fails with the current plugin?

**Comment by machow** [comment]
For some reason, everything passes now when I run the tests. I double checked by uninstalling the plugin completely and then checking with either this branch or the version available on pypi.

The version on pypi failed the new test (since it doesn't change directories), and this version passed the division by zero example. I just wanted to double check that you get the same behavior, since I can't imagine why that might be the case (based on the changes here!).

**Comment by zonca** [comment]
@machow thanks for catching that, there was actually a bug, the cell was getting an exception and the result was that every test passed...
try now.

**Comment by machow** [comment]
It looks like all the tests behaved as expected! Thanks for working on this, and contributing this plugin--it's looking really useful!

**Comment by zonca** [comment]
@machow good, thanks for reporting this issue, I think it is a good improvement to the plugin.
I would be interested in reading a blog post where you explain how you use the plugin in your use-case if you are willing to write it.
