### ISSUE TITLE
Cells being converted to string before being called, and receiving "'str' object is not callable" (pytest plugin exception)

### ISSUE THREAD

**Issue by jfraf-ddmx** [zonca/pytest-ipynb#22]
I am currently testing an web API using your very amusing framework. However, some cells appear to generate the error **pytest plugin exception: 'str' object is not callable** , what is most unusual, because the same cells, when executed on Jupyter, do not generate any exceptions. Also, sometimes it is a a different set of cells from the same document that produce such exception, passing in a run to fail in the next, without any alterations. Finally, it appears to occur mostly in the slowest-executing cells (that may take up to 20 minutes to compute).

Edit: I found [issue 20](https://github.com/zonca/pytest-ipynb/issues/20) of this project on google, and realized it might be the same error, however happening in a larger scale (20 minutes, not seconds). It might be a good idea to add a maximum-runtime argument in each cell, to be picked by the test engine

**Comment by zonca** [comment]
thanks, can you prepare a test document that fails often? so I can try to reproduce on my machine

**Comment by zonca** [comment]
got no answer, closing
