### ISSUE TITLE
Can we skip a cell in the notebook?

### ISSUE THREAD

**Issue by quang-ha** [zonca/pytest-ipynb#23]
Is there a way to skip a cell when running the unit test?

**Comment by zonca** [comment]
You can use this feature:

Add SKIPCI to a cell description to skip the test on Travis-CI (checks if
the CI environment variable is defined)

**Comment by quang-ha** [comment]
Sorry I didn't make myself very clear - what I meant was is there a way to execute `py.test -v` in cell 0 of the notebook and have the subsequent cells including the unit test? This is kind of helpful when executing the notebooks on the cloud server (for example on Microsoft Azure). After some experiments I have learnt that it doesn't like it when I included `py.test -v` in the first cell of the notebook. Any workaround or possible solution?

**Comment by quang-ha** [comment]
Perhaps a picture to illustrate what I was trying to achieve: [https://postimg.org/image/5k91m2twv/](url)

**Comment by zonca** [comment]
no sorry, the purpose of this plugin is to run from the terminal, you can open the  terminal embedded in the notebook server if your provider supports that.
