### ISSUE TITLE
How do you configure py.test to discover Jupyter notebooks other than default test*

### ISSUE THREAD

**Issue by krokha72** [zonca/pytest-ipynb#25]
Hi,
Its not an issue but rather configuration question
How do you configure py.test to discover Jupyter notebooks other than default test*
for example I would like to run tests for ALL notebooks in current folder and recursively for all sub-folders.
Could you advise how to do that if possible at all.
Thank you
-Alex

**Comment by zonca** [comment]
it is not configurable, you should modify the source, see https://github.com/zonca/pytest-ipynb/blob/master/pytest_ipynb/plugin.py#L44

**Comment by krokha72** [comment]
Got you. Thanks a lot for update. I will close the issue.
