### ISSUE TITLE
pytest does not find my all notebooks

### ISSUE THREAD

**Issue by chmduquesne** [zonca/pytest-ipynb#27]
Hi,

I am trying to use your plugin to run my tests. I have 80 tests in 21 notebooks, but on travis, pytest only finds the top-level one.

The tests are [here](https://github.com/chmduquesne/quickviz/tree/master/quickviz/tests/seaborn)

If I launch py.test on my machine, they are all found and executed. On travis they are not detected (see for example [latest build](https://travis-ci.org/chmduquesne/quickviz/jobs/420324472).

Any idea why?

**Comment by zonca** [comment]
it looks like it is not entering into the subfolder, however I don't have time to try reproduce this myself and debug it. My guess it is that you are using 2 different `py.test` versions and the one on your machine is configured to enter all subfolders but the one on travis not.

**Comment by chmduquesne** [comment]
I don't know why it is like this.

The fix I found is to force the search path in pytest.ini.

    [pytest]
    addopts = -v --doctest-modules
    testpaths = ./quickviz/tests/ ./quickviz/tests/seaborn/

This seems to do the trick.
